[package]
name = "unbound-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "unbound"
path = "src/main.rs"

[dependencies]
unbound-shared.workspace = true
bevy.workspace = true
bevy_stdb.workspace = true
spacetimedb-sdk.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { workspace = true, features = ["wayland"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { workspace = true, features = ["webgpu"] }
bevy_stdb = { workspace = true, features = ["browser"] }
spacetimedb-sdk = { workspace = true, features = ["browser"] }
console_error_panic_hook = "0.1"
getrandom = { version = "0.4", features = ["wasm_js"] }
getrandom_03 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }
