// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dummy_type::Dummy;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dummy`.
///
/// Obtain a handle from the [`DummyTableAccess::dummy`] method on [`super::RemoteTables`],
/// like `ctx.db.dummy()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dummy().on_insert(...)`.
pub struct DummyTableHandle<'ctx> {
    imp: __sdk::TableHandle<Dummy>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `dummy`.
pub struct DummyTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for DummyTableAccessor {
    type Row = Dummy;
    type Handle<'db> = DummyTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.dummy()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dummy`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DummyTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DummyTableHandle`], which mediates access to the table `dummy`.
    fn dummy(&self) -> DummyTableHandle<'_>;
}

impl DummyTableAccess for super::RemoteTables {
    fn dummy(&self) -> DummyTableHandle<'_> {
        DummyTableHandle {
            imp: self.imp.get_table::<Dummy>("dummy"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DummyInsertCallbackId(__sdk::CallbackId);
pub struct DummyDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for DummyTableHandle<'ctx> {
    type Row = Dummy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dummy> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for DummyTableHandle<'ctx> {
    type Row = Dummy;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Dummy> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DummyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DummyInsertCallbackId {
        DummyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DummyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DummyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DummyDeleteCallbackId {
        DummyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DummyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for DummyTableHandle<'ctx> {
    type InsertCallbackId = DummyInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DummyInsertCallbackId {
        DummyInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DummyInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for DummyTableHandle<'ctx> {
    type DeleteCallbackId = DummyDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DummyDeleteCallbackId {
        DummyDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DummyDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DummyUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DummyTableHandle<'ctx> {
    type UpdateCallbackId = DummyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DummyUpdateCallbackId {
        DummyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DummyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for DummyTableHandle<'ctx> {
    type UpdateCallbackId = DummyUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DummyUpdateCallbackId {
        DummyUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DummyUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `dummy`,
/// which allows point queries on the field of the same name
/// via the [`DummyIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dummy().id().find(...)`.
pub struct DummyIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Dummy, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DummyTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `dummy`.
    pub fn id(&self) -> DummyIdUnique<'ctx> {
        DummyIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DummyIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Dummy> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Dummy>("dummy");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Dummy>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Dummy>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Dummy`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dummyQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Dummy`.
    fn dummy(&self) -> __sdk::__query_builder::Table<Dummy>;
}

impl dummyQueryTableAccess for __sdk::QueryTableAccessor {
    fn dummy(&self) -> __sdk::__query_builder::Table<Dummy> {
        __sdk::__query_builder::Table::new("dummy")
    }
}
