// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dummy {
    pub id: u32,
    pub x: f32,
    pub z: f32,
    pub yaw: f32,
    pub hp: f32,
    pub action: u8,
    pub action_ticks: u8,
    pub pending_hit: bool,
    pub alive: bool,
    pub cooldown: u8,
}

impl __sdk::InModule for Dummy {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dummy`.
///
/// Provides typed access to columns for query building.
pub struct DummyCols {
    pub id: __sdk::__query_builder::Col<Dummy, u32>,
    pub x: __sdk::__query_builder::Col<Dummy, f32>,
    pub z: __sdk::__query_builder::Col<Dummy, f32>,
    pub yaw: __sdk::__query_builder::Col<Dummy, f32>,
    pub hp: __sdk::__query_builder::Col<Dummy, f32>,
    pub action: __sdk::__query_builder::Col<Dummy, u8>,
    pub action_ticks: __sdk::__query_builder::Col<Dummy, u8>,
    pub pending_hit: __sdk::__query_builder::Col<Dummy, bool>,
    pub alive: __sdk::__query_builder::Col<Dummy, bool>,
    pub cooldown: __sdk::__query_builder::Col<Dummy, u8>,
}

impl __sdk::__query_builder::HasCols for Dummy {
    type Cols = DummyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DummyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            action_ticks: __sdk::__query_builder::Col::new(table_name, "action_ticks"),
            pending_hit: __sdk::__query_builder::Col::new(table_name, "pending_hit"),
            alive: __sdk::__query_builder::Col::new(table_name, "alive"),
            cooldown: __sdk::__query_builder::Col::new(table_name, "cooldown"),
        }
    }
}

/// Indexed column accessor struct for the table `Dummy`.
///
/// Provides typed access to indexed columns for query building.
pub struct DummyIxCols {
    pub id: __sdk::__query_builder::IxCol<Dummy, u32>,
}

impl __sdk::__query_builder::HasIxCols for Dummy {
    type IxCols = DummyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DummyIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dummy {}
