// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GatherNode {
    pub id: u32,
    pub kind: u8,
    pub x: f32,
    pub z: f32,
    pub charges: u8,
    pub cooldown: u16,
}

impl __sdk::InModule for GatherNode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GatherNode`.
///
/// Provides typed access to columns for query building.
pub struct GatherNodeCols {
    pub id: __sdk::__query_builder::Col<GatherNode, u32>,
    pub kind: __sdk::__query_builder::Col<GatherNode, u8>,
    pub x: __sdk::__query_builder::Col<GatherNode, f32>,
    pub z: __sdk::__query_builder::Col<GatherNode, f32>,
    pub charges: __sdk::__query_builder::Col<GatherNode, u8>,
    pub cooldown: __sdk::__query_builder::Col<GatherNode, u16>,
}

impl __sdk::__query_builder::HasCols for GatherNode {
    type Cols = GatherNodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GatherNodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            charges: __sdk::__query_builder::Col::new(table_name, "charges"),
            cooldown: __sdk::__query_builder::Col::new(table_name, "cooldown"),
        }
    }
}

/// Indexed column accessor struct for the table `GatherNode`.
///
/// Provides typed access to indexed columns for query building.
pub struct GatherNodeIxCols {
    pub id: __sdk::__query_builder::IxCol<GatherNode, u32>,
}

impl __sdk::__query_builder::HasIxCols for GatherNode {
    type IxCols = GatherNodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GatherNodeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GatherNode {}
