// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub drawn: bool,
    pub hp: f32,
    pub stamina: f32,
    pub loadout: u8,
    pub action: u8,
    pub action_ticks: u8,
    pub pending_hit: bool,
    pub alive: bool,
    pub name: String,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub x: __sdk::__query_builder::Col<Player, f32>,
    pub y: __sdk::__query_builder::Col<Player, f32>,
    pub z: __sdk::__query_builder::Col<Player, f32>,
    pub yaw: __sdk::__query_builder::Col<Player, f32>,
    pub drawn: __sdk::__query_builder::Col<Player, bool>,
    pub hp: __sdk::__query_builder::Col<Player, f32>,
    pub stamina: __sdk::__query_builder::Col<Player, f32>,
    pub loadout: __sdk::__query_builder::Col<Player, u8>,
    pub action: __sdk::__query_builder::Col<Player, u8>,
    pub action_ticks: __sdk::__query_builder::Col<Player, u8>,
    pub pending_hit: __sdk::__query_builder::Col<Player, bool>,
    pub alive: __sdk::__query_builder::Col<Player, bool>,
    pub name: __sdk::__query_builder::Col<Player, String>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            drawn: __sdk::__query_builder::Col::new(table_name, "drawn"),
            hp: __sdk::__query_builder::Col::new(table_name, "hp"),
            stamina: __sdk::__query_builder::Col::new(table_name, "stamina"),
            loadout: __sdk::__query_builder::Col::new(table_name, "loadout"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            action_ticks: __sdk::__query_builder::Col::new(table_name, "action_ticks"),
            pending_hit: __sdk::__query_builder::Col::new(table_name, "pending_hit"),
            alive: __sdk::__query_builder::Col::new(table_name, "alive"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
