// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerInput {
    pub identity: __sdk::Identity,
    pub dir_x: f32,
    pub dir_z: f32,
    pub yaw: f32,
    pub drawn: bool,
    pub buttons: u32,
    pub loadout: u8,
    pub pitch: f32,
}

impl __sdk::InModule for PlayerInput {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerInput`.
///
/// Provides typed access to columns for query building.
pub struct PlayerInputCols {
    pub identity: __sdk::__query_builder::Col<PlayerInput, __sdk::Identity>,
    pub dir_x: __sdk::__query_builder::Col<PlayerInput, f32>,
    pub dir_z: __sdk::__query_builder::Col<PlayerInput, f32>,
    pub yaw: __sdk::__query_builder::Col<PlayerInput, f32>,
    pub drawn: __sdk::__query_builder::Col<PlayerInput, bool>,
    pub buttons: __sdk::__query_builder::Col<PlayerInput, u32>,
    pub loadout: __sdk::__query_builder::Col<PlayerInput, u8>,
    pub pitch: __sdk::__query_builder::Col<PlayerInput, f32>,
}

impl __sdk::__query_builder::HasCols for PlayerInput {
    type Cols = PlayerInputCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerInputCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            dir_x: __sdk::__query_builder::Col::new(table_name, "dir_x"),
            dir_z: __sdk::__query_builder::Col::new(table_name, "dir_z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            drawn: __sdk::__query_builder::Col::new(table_name, "drawn"),
            buttons: __sdk::__query_builder::Col::new(table_name, "buttons"),
            loadout: __sdk::__query_builder::Col::new(table_name, "loadout"),
            pitch: __sdk::__query_builder::Col::new(table_name, "pitch"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerInput`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerInputIxCols {
    pub identity: __sdk::__query_builder::IxCol<PlayerInput, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PlayerInput {
    type IxCols = PlayerInputIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerInputIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerInput {}
