// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetInputArgs {
    pub dir_x: f32,
    pub dir_z: f32,
    pub yaw: f32,
    pub drawn: bool,
}

impl From<SetInputArgs> for super::Reducer {
    fn from(args: SetInputArgs) -> Self {
        Self::SetInput {
            dir_x: args.dir_x,
            dir_z: args.dir_z,
            yaw: args.yaw,
            drawn: args.drawn,
        }
    }
}

impl __sdk::InModule for SetInputArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_input {
    /// Request that the remote module invoke the reducer `set_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_input:set_input_then`] to run a callback after the reducer completes.
    fn set_input(&self, dir_x: f32, dir_z: f32, yaw: f32, drawn: bool) -> __sdk::Result<()> {
        self.set_input_then(dir_x, dir_z, yaw, drawn, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_input` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_input_then(
        &self,
        dir_x: f32,
        dir_z: f32,
        yaw: f32,
        drawn: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_input for super::RemoteReducers {
    fn set_input_then(
        &self,
        dir_x: f32,
        dir_z: f32,
        yaw: f32,
        drawn: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetInputArgs {
                dir_x,
                dir_z,
                yaw,
                drawn,
            },
            callback,
        )
    }
}
