// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Character {
    pub identity: __sdk::Identity,
    pub name: String,
    pub melee_xp: u64,
    pub ranged_xp: u64,
    pub magic_xp: u64,
    pub defence_xp: u64,
    pub hitpoints_xp: u64,
    pub gather_xp: u64,
    pub loadout: u8,
}

impl __sdk::InModule for Character {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Character`.
///
/// Provides typed access to columns for query building.
pub struct CharacterCols {
    pub identity: __sdk::__query_builder::Col<Character, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Character, String>,
    pub melee_xp: __sdk::__query_builder::Col<Character, u64>,
    pub ranged_xp: __sdk::__query_builder::Col<Character, u64>,
    pub magic_xp: __sdk::__query_builder::Col<Character, u64>,
    pub defence_xp: __sdk::__query_builder::Col<Character, u64>,
    pub hitpoints_xp: __sdk::__query_builder::Col<Character, u64>,
    pub gather_xp: __sdk::__query_builder::Col<Character, u64>,
    pub loadout: __sdk::__query_builder::Col<Character, u8>,
}

impl __sdk::__query_builder::HasCols for Character {
    type Cols = CharacterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CharacterCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            melee_xp: __sdk::__query_builder::Col::new(table_name, "melee_xp"),
            ranged_xp: __sdk::__query_builder::Col::new(table_name, "ranged_xp"),
            magic_xp: __sdk::__query_builder::Col::new(table_name, "magic_xp"),
            defence_xp: __sdk::__query_builder::Col::new(table_name, "defence_xp"),
            hitpoints_xp: __sdk::__query_builder::Col::new(table_name, "hitpoints_xp"),
            gather_xp: __sdk::__query_builder::Col::new(table_name, "gather_xp"),
            loadout: __sdk::__query_builder::Col::new(table_name, "loadout"),
        }
    }
}

/// Indexed column accessor struct for the table `Character`.
///
/// Provides typed access to indexed columns for query building.
pub struct CharacterIxCols {
    pub identity: __sdk::__query_builder::IxCol<Character, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Character {
    type IxCols = CharacterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CharacterIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Character {}
