// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CombatEvent {
    pub kind: u8,
    pub attacker_is_dummy: bool,
    pub attacker: __sdk::Identity,
    pub dummy_id: u32,
    pub target_is_dummy: bool,
    pub target: __sdk::Identity,
    pub target_dummy: u32,
    pub damage: f32,
    pub x: f32,
    pub z: f32,
}

impl __sdk::InModule for CombatEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to columns for query building.
pub struct CombatEventCols {
    pub kind: __sdk::__query_builder::Col<CombatEvent, u8>,
    pub attacker_is_dummy: __sdk::__query_builder::Col<CombatEvent, bool>,
    pub attacker: __sdk::__query_builder::Col<CombatEvent, __sdk::Identity>,
    pub dummy_id: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub target_is_dummy: __sdk::__query_builder::Col<CombatEvent, bool>,
    pub target: __sdk::__query_builder::Col<CombatEvent, __sdk::Identity>,
    pub target_dummy: __sdk::__query_builder::Col<CombatEvent, u32>,
    pub damage: __sdk::__query_builder::Col<CombatEvent, f32>,
    pub x: __sdk::__query_builder::Col<CombatEvent, f32>,
    pub z: __sdk::__query_builder::Col<CombatEvent, f32>,
}

impl __sdk::__query_builder::HasCols for CombatEvent {
    type Cols = CombatEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CombatEventCols {
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            attacker_is_dummy: __sdk::__query_builder::Col::new(table_name, "attacker_is_dummy"),
            attacker: __sdk::__query_builder::Col::new(table_name, "attacker"),
            dummy_id: __sdk::__query_builder::Col::new(table_name, "dummy_id"),
            target_is_dummy: __sdk::__query_builder::Col::new(table_name, "target_is_dummy"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            target_dummy: __sdk::__query_builder::Col::new(table_name, "target_dummy"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
        }
    }
}

/// Indexed column accessor struct for the table `CombatEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct CombatEventIxCols {}

impl __sdk::__query_builder::HasIxCols for CombatEvent {
    type IxCols = CombatEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CombatEventIxCols {}
    }
}
