// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gather_node_type::GatherNode;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gather_node`.
///
/// Obtain a handle from the [`GatherNodeTableAccess::gather_node`] method on [`super::RemoteTables`],
/// like `ctx.db.gather_node()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gather_node().on_insert(...)`.
pub struct GatherNodeTableHandle<'ctx> {
    imp: __sdk::TableHandle<GatherNode>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `gather_node`.
pub struct GatherNodeTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GatherNodeTableAccessor {
    type Row = GatherNode;
    type Handle<'db> = GatherNodeTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.gather_node()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gather_node`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GatherNodeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GatherNodeTableHandle`], which mediates access to the table `gather_node`.
    fn gather_node(&self) -> GatherNodeTableHandle<'_>;
}

impl GatherNodeTableAccess for super::RemoteTables {
    fn gather_node(&self) -> GatherNodeTableHandle<'_> {
        GatherNodeTableHandle {
            imp: self.imp.get_table::<GatherNode>("gather_node"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GatherNodeInsertCallbackId(__sdk::CallbackId);
pub struct GatherNodeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GatherNodeTableHandle<'ctx> {
    type Row = GatherNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatherNode> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GatherNodeTableHandle<'ctx> {
    type Row = GatherNode;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GatherNode> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GatherNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherNodeInsertCallbackId {
        GatherNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatherNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GatherNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherNodeDeleteCallbackId {
        GatherNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatherNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GatherNodeTableHandle<'ctx> {
    type InsertCallbackId = GatherNodeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherNodeInsertCallbackId {
        GatherNodeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GatherNodeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GatherNodeTableHandle<'ctx> {
    type DeleteCallbackId = GatherNodeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GatherNodeDeleteCallbackId {
        GatherNodeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GatherNodeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GatherNodeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GatherNodeTableHandle<'ctx> {
    type UpdateCallbackId = GatherNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatherNodeUpdateCallbackId {
        GatherNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatherNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GatherNodeTableHandle<'ctx> {
    type UpdateCallbackId = GatherNodeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GatherNodeUpdateCallbackId {
        GatherNodeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GatherNodeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `gather_node`,
/// which allows point queries on the field of the same name
/// via the [`GatherNodeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gather_node().id().find(...)`.
pub struct GatherNodeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GatherNode, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GatherNodeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `gather_node`.
    pub fn id(&self) -> GatherNodeIdUnique<'ctx> {
        GatherNodeIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GatherNodeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GatherNode> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GatherNode>("gather_node");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GatherNode>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GatherNode>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GatherNode`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gather_nodeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GatherNode`.
    fn gather_node(&self) -> __sdk::__query_builder::Table<GatherNode>;
}

impl gather_nodeQueryTableAccess for __sdk::QueryTableAccessor {
    fn gather_node(&self) -> __sdk::__query_builder::Table<GatherNode> {
        __sdk::__query_builder::Table::new("gather_node")
    }
}
