// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub id: u32,
    pub x: f32,
    pub z: f32,
    pub vx: f32,
    pub vz: f32,
    pub owner: __sdk::Identity,
    pub from_dummy: bool,
    pub dummy_owner: u32,
    pub damage: f32,
    pub ttl: u8,
    pub skill: u8,
    pub y: f32,
    pub vy: f32,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Projectile`.
///
/// Provides typed access to columns for query building.
pub struct ProjectileCols {
    pub id: __sdk::__query_builder::Col<Projectile, u32>,
    pub x: __sdk::__query_builder::Col<Projectile, f32>,
    pub z: __sdk::__query_builder::Col<Projectile, f32>,
    pub vx: __sdk::__query_builder::Col<Projectile, f32>,
    pub vz: __sdk::__query_builder::Col<Projectile, f32>,
    pub owner: __sdk::__query_builder::Col<Projectile, __sdk::Identity>,
    pub from_dummy: __sdk::__query_builder::Col<Projectile, bool>,
    pub dummy_owner: __sdk::__query_builder::Col<Projectile, u32>,
    pub damage: __sdk::__query_builder::Col<Projectile, f32>,
    pub ttl: __sdk::__query_builder::Col<Projectile, u8>,
    pub skill: __sdk::__query_builder::Col<Projectile, u8>,
    pub y: __sdk::__query_builder::Col<Projectile, f32>,
    pub vy: __sdk::__query_builder::Col<Projectile, f32>,
}

impl __sdk::__query_builder::HasCols for Projectile {
    type Cols = ProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectileCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vz: __sdk::__query_builder::Col::new(table_name, "vz"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            from_dummy: __sdk::__query_builder::Col::new(table_name, "from_dummy"),
            dummy_owner: __sdk::__query_builder::Col::new(table_name, "dummy_owner"),
            damage: __sdk::__query_builder::Col::new(table_name, "damage"),
            ttl: __sdk::__query_builder::Col::new(table_name, "ttl"),
            skill: __sdk::__query_builder::Col::new(table_name, "skill"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
        }
    }
}

/// Indexed column accessor struct for the table `Projectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectileIxCols {
    pub id: __sdk::__query_builder::IxCol<Projectile, u32>,
}

impl __sdk::__query_builder::HasIxCols for Projectile {
    type IxCols = ProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectileIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Projectile {}
